// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROBOSEARCH;


public class Coordinate {

	/**
	 * 
	 */
	private int latitude;
	/**
	 * 
	 */
	private int longitude;
	/**
	 * 
	 */
	private boolean hasBeenVisited = false;
	/**
	 * 
	 * @param latitude 
	 * @param longitude 
	 */
	public Coordinate(int latitude, int longitude) {
		this.latitude = latitude;
		this.longitude = longitude;
	}

	/**
	 * 
	 * @return 
	 */
	public int getLatitude() {
		return this.latitude;
	}

	/**
	 * 
	 * @return 
	 */
	public int getLongitude() {
		return this.longitude;
	}

	/**
	 * 
	 * @param longitude 
	 */
	public void setLongitude(int longitude) {
		this.longitude = longitude;
	}

	/**
	 * 
	 * @param latitude 
	 */
	public void setLatitude(int latitude) {
		this.latitude = latitude;
	}
	/**
	 * 
	 * @return 
	 */
	public void setCoordinateHasBeenVisited(){
		this.hasBeenVisited = true;
	}
	/**
	 * 
	 * @return 
	 */
	public boolean getCoordinateHasBeenVisited(){
		return this.hasBeenVisited;
	}
	
	public void printCoordinate(){
		System.out.printf("(%d, %d)", latitude, longitude);
	}
};