// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROBOSEARCH;

import simbad.sim.EnvironmentDescription;
import simbad.sim.Box;
import simbad.sim.Wall;
import javax.vecmath.Vector3f;
import javax.vecmath.Vector3d;
import javax.vecmath.Color3f;
import java.awt.Color;

public class Environment extends EnvironmentDescription {

	/**
	 * 
	 */
	private int wallWidth = 21;
	/**
	 * 
	 */
	private int wallHeight = 4;
	/**
	 * 
	 */
	private int worldSize = 25;
	
	/**
	 * 
	 */
	public Environment() {
		
		this.light1IsOn = true;
		this.light2IsOn = true;		
		this.light1SetPosition(-20.0, 5.0, 0);
		
		this.setWorldSize(worldSize); 		
		// show the axis
		this.showAxis(true);
		// enable physics engine
		this.setUsePhysics(true);
		
		this.makeWall(new Vector3d(-10.5, 0, 0), wallWidth, wallHeight, Color.white, true);
		this.makeWall(new Vector3d(10.5, 0, 0), wallWidth, wallHeight, Color.white, true);
		this.makeWall(new Vector3d(0, 0, -10.5), wallWidth, wallHeight, Color.white, false);
		this.makeWall(new Vector3d(0, 0, 10.5), wallWidth, wallHeight, Color.white, false);
	}

	/**
	 * 
	 * @return 
	 */
	public int getWorldSize() {
		return this.worldSize;
	}

	/**
	 * 
	 * @param position 
	 * @param width 
	 * @param height  
	 * @param color 
	 * @param rotate 
	 */
	public void makeWall(Vector3d position, int width, int height, Color color, boolean rotate) {
		Wall wall = new Wall(position, width, height, this);
		wall.setColor(new Color3f(color));
		if (rotate){
			wall.rotate90(1);
		}
		add(wall);
	}

	/**
	 * 
	 * @param position 
	 * @param size 
	 * @param color 
	 */
	public void makeBox(Vector3d position, Vector3f size, Color color) {
		Box box = new Box(position, size, this);
		box.setColor(new Color3f(color));
		add(box);
	}
};
