// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROBOSEARCH;

/**
 * 
 */
public enum mode {
	/**
	 * 
	 */
	AVOID_OBSTACLE,
	/**
	 * 
	 */
	FOLLOW_PATH,
	/**
	 * 
	 */
	IDLE;
};
