// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROBOSEARCH;

import ROBOSEARCH.Subject;

/************************************************************/
/**
 * 
 */
public interface Observer {
	/**
	 * 
	 */
	public Subject subject = null;

	/**
	 * 
	 */
	public void update();
};
