// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROBOSEARCH;

import java.awt.Color;


import ROBOSEARCH.Rover;
import ROBOSEARCH.Task;


/************************************************************/
/**
 * 
 */
public class RoverFactory {
	/**
	 * 
	 */
	private int roverCounter;

	/**
	 * 
	 * @param task 
	 * @return 
	 * @param startPosition 
	 */
	public Rover createRover(Task task, Color[] searchColors) {
		Rover rover =  new Rover(String.valueOf(roverCounter), task, searchColors);
	    this.roverCounter++;
		return rover;
	}

	/**
	 * 
	 */
	public RoverFactory() {
		roverCounter = 0;
	}
};
