// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROBOSEARCH;

import ROBOSEARCH.Observer;

/************************************************************/
/**
 * 
 */
public interface Subject {
	/**
	 * 
	 */
	public int state = 0;
	/**
	 * 
	 */
	public Observer[] observers = null;

	/**
	 * 
	 * @return 
	 */
	public int getState();

	/**
	 * 
	 * @param state 
	 */
	public void setState(int state);

	/**
	 * 
	 * @param observer 
	 */
	public void attach(Observer observer);

	/**
	 * 
	 * @param observer 
	 */
	public void detach(Observer observer);

	/**
	 * 
	 */
	public void notifyEverybody();
};
